<?php

namespace UserBundle\Entity;

use UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	/** Return the total number of user */
	public function getTotalUser()
	{
		$qb = $this->createQueryBuilder('u');
		$qb->select('COUNT(u)');

		return $qb->getQuery()->getSingleScalarResult();
	}

	/** Return the total number of user */
	public function getTotalAuthor()
	{
		$role = "ROLE_AUTHOR";

		$qb = $this->_em->createQueryBuilder();
		$qb->select('count(u)')
			->from($this->_entityName, 'u')
			->where('u.roles LIKE :roles')
			->setParameter('roles', '%"'.$role.'"%');

		return $qb->getQuery()->getSingleScalarResult();
	}

	/** Function return a list of user */
	public function getUser($where, $order = null, $limit = null, $offset = null) {
		return $this->findBy(
			$where,
			$order,
			$limit,
			$offset
		);
	}

	public function getAllUserExcept(User $user, $offset, $limit)
	{

		$qb = $this->createQueryBuilder('u');
		$qb->add('where',$qb->expr()->not(
				$qb->expr()->eq('u.id', ':idUser')
			))
			->setParameter('idUser', $user->getId())
			->orderBy('u.id', 'DESC')
			->setFirstResult($offset)
			->setMaxResults($limit);

		return $qb->getQuery()->getResult();
	}
}