<?php

namespace AppBundle\Entity;

/**
 * FixRssRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FluxRssRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotalFluxRss()
	{
		$qb = $this->createQueryBuilder('a');
        $qb->select('COUNT(a)');

        return $qb->getQuery()->getSingleScalarResult();
	}

    public function getFluxRss($where, $order = null, $limit = null, $offset = null)
    {
        if (!$where)
            $where = array();

        return $fluxRss = $this->findBy(
                $where,
                $order,
                $limit,
                $offset
            );
    }
}