<?php

namespace AppBundle\Entity;

/**
 * RssEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RssEntityRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTotalRssEntityByFluxRss($fluxRss)
	{
		$qb = $this->createQueryBuilder('e');
        $qb->select('COUNT(e)')
            ->InnerJoin('e.fluxRss', 'f')
            ->where('f = :fluxRss')
            ->setParameter('fluxRss', $fluxRss);

        return $qb->getQuery()->getSingleScalarResult();
	}

    public function getRssEntityByFluxRss($fluxRss)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->InnerJoin('e.fluxRss', 'f')
            ->where('f = :fluxRss')
            ->setParameter('fluxRss', $fluxRss);
        
        return $qb->getQuery()->getResult();
    }
}